---
- name: Create and distribute MUNGE key, then verify cluster auth
  hosts: all
  become: true
  gather_facts: false

  vars:
    controller_host: controller
    munge_dir: /etc/munge
    munge_key_path: /etc/munge/munge.key

  pre_tasks:
    - name: Ensure /etc/munge exists on every host
      ansible.builtin.file:
        path: "{{ munge_dir }}"
        state: directory
        owner: munge
        group: munge
        mode: "0700"

  tasks:
    # --- Create key ONCE on controller, like your manual steps ---
    - name: Generate MUNGE key on controller if missing (sudo create-munge-key)
      ansible.builtin.command: create-munge-key
      args:
        creates: "{{ munge_key_path }}"
      delegate_to: "{{ controller_host }}"
      run_once: true

    - name: Secure permissions on controller key (chown/chmod)
      ansible.builtin.file:
        path: "{{ munge_key_path }}"
        owner: munge
        group: munge
        mode: "0400"
      delegate_to: "{{ controller_host }}"
      run_once: true

    # --- Distribute the key to everyone (controller + workers) ---
    - name: Read controller key (base64)
      ansible.builtin.slurp:
        src: "{{ munge_key_path }}"
      delegate_to: "{{ controller_host }}"
      run_once: true
      register: munge_key_b64

    - name: Copy MUNGE key to all hosts (like scp)
      ansible.builtin.copy:
        content: "{{ munge_key_b64.content | b64decode }}"
        dest: "{{ munge_key_path }}"
        owner: munge
        group: munge
        mode: "0400"

    # --- Enable and start munge everywhere ---
    - name: Enable and start munge
      ansible.builtin.service:
        name: munge
        enabled: true
        state: started

    # --- Cross-node verification: munge on controller | ssh host unmunge ---
    - name: Build list of peer IPs for SSH checks
      ansible.builtin.set_fact:
        peer_ips: >-
          {{ groups['all']
             | map('extract', hostvars)
             | map(attribute='ansible_host', default=None)
             | list }}

      delegate_to: "{{ controller_host }}"
      run_once: true

    - name: Verify MUNGE across cluster (controller -> each host)
      ansible.builtin.shell: |
        set -euo pipefail
        munge -n | ssh -o StrictHostKeyChecking=no root@{{ item }} unmunge > /dev/null
      args:
        executable: /bin/bash
      loop: "{{ peer_ips | difference([omit]) }}"
      delegate_to: "{{ controller_host }}"
      run_once: true
