---
- name: Install & configure slurmdbd and accounting
  hosts: controllers
  become: true
  gather_facts: true

  vars:
    controller_host: controller
    db_name: slurm_acct_db
    db_user: slurm
    db_pass: "CHANGE_ME_STRONG"        # put in Ansible Vault later
    db_host: localhost
    db_port: 3306
    slurmdbd_port: 6819
    cluster_name: solidigm-hpc
    slurmdbd_log: /var/log/slurmdbd.log
    slurmdbd_conf: /etc/slurm/slurmdbd.conf

  pre_tasks:
    - name: Ensure dnf cache & EPEL present
      ansible.builtin.dnf:
        name:
          - epel-release
          - epel-next-release
        state: present
      failed_when: false

  tasks:
    - name: Install MariaDB server and slurmdbd
      ansible.builtin.dnf:
        name:
          - mariadb-server
          - slurm-slurmdbd       # package name on Rocky/EPEL
        state: present

    - name: Enable & start MariaDB
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

    - name: Create accounting DB and user (idempotent)
      ansible.builtin.shell: |
        set -euo pipefail
        mysql -u root <<'SQL'
        CREATE DATABASE IF NOT EXISTS {{ db_name }};
        CREATE USER IF NOT EXISTS '{{ db_user }}'@'{{ db_host }}' IDENTIFIED BY '{{ db_pass }}';
        GRANT ALL ON {{ db_name }}.* TO '{{ db_user }}'@'{{ db_host }}';
        FLUSH PRIVILEGES;
        SQL
      args:
        executable: /bin/bash

    - name: Ensure slurmdbd log file exists
      ansible.builtin.file:
        path: "{{ slurmdbd_log }}"
        state: touch
        owner: slurm
        group: slurm
        mode: "0644"

    - name: Write /etc/slurm/slurmdbd.conf
      ansible.builtin.template:
        src: templates/slurmdbd.conf.j2
        dest: "{{ slurmdbd_conf }}"
        owner: slurm
        group: slurm
        mode: "0600"
      notify: Restart slurmdbd

    - name: Open port {{ slurmdbd_port }} if firewalld is running
      ansible.builtin.shell: |
        if systemctl is-active --quiet firewalld; then
          firewall-cmd --add-port={{ slurmdbd_port }}/tcp --permanent
          firewall-cmd --reload
        fi
      args:
        executable: /bin/bash
      changed_when: false
      failed_when: false

    - name: Enable & start slurmdbd
      ansible.builtin.service:
        name: slurmdbd
        state: started
        enabled: true

    - name: Wait for slurmdbd to listen
      ansible.builtin.wait_for:
        host: "{{ controller_host }}"
        port: "{{ slurmdbd_port }}"
        timeout: 30

    - name: Register cluster in accounting (safe if already present)
      ansible.builtin.shell: |
        sacctmgr -n -p show cluster | grep -q '^{{ cluster_name }}|' \
          || sacctmgr -i add cluster {{ cluster_name }}
      args:
        executable: /bin/bash

    - name: Restart slurmctld (pick up accounting)
      ansible.builtin.service:
        name: slurmctld
        state: restarted

  handlers:
    - name: Restart slurmdbd
      ansible.builtin.service:
        name: slurmdbd
        state: restarted
